.\" hw8 Encode man page
.\" James Capuder - Fall 2016

.TH encode 1 "28 November 2016" "CSCI 241" "Oberlin College"

.SH NAME
.B encode
\- a huffman based compression program

.SH SYNOPSIS
.B encode
<filename>
[ outfile ]

.SH DESCRIPTION
Compresses <filename> using the Huffman compression algorithm, optionally writing to an output file. 

.SH OPTIONS
.IP "outfile"
File to write the compressed input to. if none specified, will write to stdout.

.SH AUTHOR
James Capuder (Fall 2016)

.SH BUGS
No bugs.
